### ISSUE TITLE
Blog Post Ideas - Running Ticket

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/ops#100]
Various ideas for blog posts and other DKAN related content:

Content strategies:
- Create tweet asks for followers
- Tweet no fewer than 3 times a day
- Post content on multiple platforms
- Create an editorial calendar for social media posts
- Make sure calendar includes DKAN tip tweets

- DKAN uses around the world, including but not limited to:
 - Anti-Mafia efforts in Italy
 - German DKAN site that made Alexa app
 - Anti-trafficking/violence NGOs in Eastern Europe
 - DKAN in Africa (interview John Eromosele, using it in Nigeria)

**Comment by lukefretwell** [comment]
Added to https://github.com/GetDKAN/ops/issues/19 and closing this.

Create a content strategy doc and will add ideas section and include these.
