### ISSUE TITLE
Send DKAN January newsletter

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#103]
- [ ] include in issue-template
- [ ] update wiki with better context: https://github.com/GetDKAN/ops/wiki/Newsletter

**Comment by lukefretwell** [comment]
via @kimwdavidson:

Having that one bullet point under news looks a bit weird. Just make it a second news item
Both DKAN roadmap links go to the same place, stick with one
Same with Open Data Day
Let's add a little text to join the open data community: "We're talking about about how best to use DKAN, helping solve each other's challenges, and finding new ways to work together. Come join the conversation!" or something

**Comment by lukefretwell** [comment]
@kimwdavidson note there are two different links on Open Data Day and Hack DKAN.

**Comment by kimwdavidson** [comment]
Let's just get a little more teaser text in there. 

For the second news item:
**Encouraging adoption of free and open source software in Open Data policy.**
Government institutions frequently ask for public comment on their open data policies. We're working on a templated response that anyone can use to encourage their governments to look to free and open source software. Take a look and help us make it even more compelling.

**DKAN Powered**
We see government agencies doing amazing things with their data every day. Visit the US Department of Health and Human Service's DKAN open data portal to see how they're contributing to the open data world. 

**Events**
We're participating in Open Data Day on March 3, 2018. All over the world, local events will mobilize citizens and organizations to improve their world through data. Learn how you can join us and Hack DKAN.
