### ISSUE TITLE
Send DKAN Summit follow-up attendee thank you

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#12]

**Comment by melindaburgess** [comment]
@aaronpava @stefaniefgray Additions or comments are welcome - I shared the draft with you

**Comment by melindaburgess** [comment]
https://docs.google.com/document/d/11E0x7r0f4k7e3_eSuSk0k1czsbMiI1mKiLNsDAB8Rj8/edit

**Comment by lukefretwell** [comment]
@melindaburgess done
