### ISSUE TITLE
Ideas for DKAN Open Data Summit 2018

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#130]
Add your ideas for making DKAN Open Data Summit 2018 💥 .

**Comment by kimwdavidson** [comment]
Idea dump:
- DKAN last year in review
- client presentations (California, USDA?)
- trends in open data generally
- coworking on prioritizing upcoming features
- how to contribute
- BOF lunch
- snack table

let's ask Slack

**Comment by kimwdavidson** [comment]
A spot or two for community submitted sessions?
