### ISSUE TITLE
Set up registration (2018 DKAN Summit)

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#138]
- [ ] Make copy of 2017 reg, edit accordingly
- [ ] Embed/link to from /summit page
- [ ] Send announcement to past attendees

**Comment by kimwdavidson** [comment]
Need:
- [x] Description
- [x] Location (Natcher Conference Center - Room C1/C2)
- [x] Start and end time (1-4pm)
- [x] Capacity (50)

**Comment by kimwdavidson** [comment]
@lukefretwell I set this up: https://www.eventbrite.com/e/dkan-summit-2018-at-drupal-govcon-tickets-47932975821

Could use an eyeball on the details and a better image. Can you do that?

**Comment by lukefretwell** [comment]
@kimwdavidson did you set this up under the Project DKAN account? I see a different, uncompleted one in there from the link above.

https://www.eventbrite.com/e/2018-dkan-open-data-summit-tickets-36891515516

**Comment by lukefretwell** [comment]
@kimwdavidson see also the DKAN page:

https://www.eventbrite.com/o/dkan-14793986036

Let me know if you need access to this.

**Comment by kimwdavidson** [comment]
@lukefretwell I need access - even the date is wrong on this one. I'll update it. Can you just eyeball the description?

**Comment by lukefretwell** [comment]
@kimwdavidson I resent creds. Did you receive?

**Comment by lukefretwell** [comment]
@kimwdavidson suggested minor description edits:

The 2018 DKAN Summit brings together the Drupal open data community to share, collaborate, and learn about using DKAN to support their open source open data efforts. We'll discuss what's new in DKAN, open data, and what's in store the future. We'll also work together to develop ideas for improvements to the platform, share what community members are working on, and discuss how to get involved in contributing to the project. You'll make lots of great connections to other members of the open source open data community, learn best practices, and contribute toward creating a better platform for everyone.

**Comment by kimwdavidson** [comment]
Link here: https://www.eventbrite.com/e/2018-dkan-open-data-summit-tickets-36891515516
