### ISSUE TITLE
Room logistics (2018 DKAN Summit)

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#139]
Items to order:

- [x] Big post-it pad (3)
- [x] Sharpies (10 pack)
- [ ] Snacks (will grocery shop there)

Questions:

- Is this the same room as last year?
- What is the room max capacity?
- What AV equipment is made available?

**Comment by prynncamm** [comment]
Hey @lukefretwell !

- It is **not** the same room as last year. Last year you were in room D, this year you are in room C1/C2. --> 
![screen shot 2018-07-06 at 9 42 00 pm](https://user-images.githubusercontent.com/831098/42405513-535b2308-8165-11e8-8d09-bdbf6977feaf.png)

- The room max capacity is 30 classroom style and 50 lecture style. Let me know what style you'd prefer!

- A/V equipment provided is a projector and screen and podium microphone. You will need to bring a laptop (or another device) and an adaptor.

**Comment by lukefretwell** [comment]
@prynncamm we'll do lecture style. Thank you!

**Comment by prynncamm** [comment]
@lukefretwell and @kimwdavidson - I heard back from Jess that because of room logistics, we're not able to do lecture style for those rooms and she updated the room capacity to 28. 

Can you make that work? Is there anything I can do to help?

**Comment by kimwdavidson** [comment]
@prynncamm We'll be fine. Thanks for checking!

**Comment by lukefretwell** [comment]
@kimwdavidson can get add specifics to the items order list in the first comment?

**Comment by kimwdavidson** [comment]
@lukefretwell or judy to order to bill

**Comment by lukefretwell** [comment]
@kimwdavidson ordered and sent to Bill. Closing out, but just a reminder on the snacks. Make sure they're healthy!
