### ISSUE TITLE
Consider goals/intentions for takeaways post-DKAN Summit (2018 DKAN Summit)

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/ops#148]
What do we want attendees to learn/come away with?

**Comment by kimwdavidson** [comment]
Audience
- DKAN community (users, vendors)
- developers who are interested in contributing
- Non-developers interested in contributing
- open data enthusiasts

Goals
- Encourage interaction between members of the community
- Show DKAN progress over the last year
- Share how to get engaged in the community
- Show what the community can offer
- Share how to contribute
--- contribute feedback
--- contribute code
--- share DKAN
- Collect feedback and priorities from attendees
--- How do we support the open data community
--- How do we make the product better
--- How do we make the community more useful
