### ISSUE TITLE
Complete Drupal GovCon spreadsheet (2018 DKAN Summit)

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#149]
From Amy:

Hi Guys!

I just wanted to check in on a couple missing items for DKAN Summit.

We need - 
A short description for marketing materials
A link to where people can sign up (Eventbrite or another site of your choosing)
If you could head on over to [this spreadsheet](https://docs.google.com/spreadsheets/d/14Em0s7EUU--khTETE38baMvL7yphm00-qwwMBVsqz5E/edit#gid=0) and fill out your information by the end of the day Friday, July 13th we'll be able to get your session marketed and into the schedules of our attendees!

Please let me know if you have any questions.

**Comment by kimwdavidson** [comment]
Eventbrite sign up: https://www.eventbrite.com/e/dkan-summit-2018-at-drupal-govcon-tickets-47932975821

Description:
The DKAN summit brings together the Drupal Open Data community to share, collaborate, and learn about using DKAN to support their open source open data efforts. We'll discuss what's new in DKAN and what's in store the future. We'll also work together to develop ideas for improvements to the platform, share what community members are working on, and discuss how to get involved in contributing to the project. You'll make lots of great connections to other members of the open source open data community, learn best practices, and contribute toward creating a better platform for everyone

**Comment by kimwdavidson** [comment]
Now wondering if we should use a Google form, so we can collect info about their organization and role?

**Comment by lukefretwell** [comment]
@kimwdavidson via email from DGC: 

https://docs.google.com/spreadsheets/u/4/d/14Em0s7EUU--khTETE38baMvL7yphm00-qwwMBVsqz5E/edit?mc_cid=2489e46fd2&mc_eid=7905abd535#gid=0

Drupal GovCon Training Sessions
Hi,

We are still missing training information. If you have not done so, please fill in the requested training session information today.

Training Session Spreadsheet

Thanks.
