### ISSUE TITLE
Add people to DKAN GitHub org/team

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#15]
@sheldonrampton can we get @grugnog added as an or admin?

https://github.com/orgs/GetDKAN/people

**Comment by grugnog** [comment]
I am an admin now! What people do we need to add (bearing in mind that it is $9/month each)?

**Comment by lukefretwell** [comment]
@grugnog not sure who else should be added, but probably good to do all at once.

Why $9? Aren't all these repos public?

Can we add the following to this org as members:

* @nerdstein
* @aaronpava 
* @stefaniefgray 
* @melindaburgess

**Comment by grugnog** [comment]
I was wondering that also - I guess someone has a private repo at some point (or just liked paying for Github?).

I went ahead and downgraded to a free account and I have added these 4. I also added them to CivicActions and Website teams.

**Comment by lukefretwell** [comment]
@grugnog thank you!

Can you also add @openprivacy (and then can just close this ticket)?
