### ISSUE TITLE
Add Sprint Day info to /summit (2018 DKAN Summit)

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#153]
What we need:

* Date/time/location
* Short description (who should attend, what will happen)

https://getdkan.org/summit/

**Comment by lukefretwell** [comment]
@dafeder see Q for you ☝️

**Comment by lukefretwell** [comment]
@dafeder do we have this info?

**Comment by lukefretwell** [comment]
@dafeder closing this issue, move to https://github.com/GetDKAN/ops/issues/153

**Comment by dafeder** [comment]
@lukefretwell I think this issue got lost somehow - the comment above just links the ticket to itself. Not sure if there is another issue floating around somewhere but after much delay and confusion, here is some copy for the sprint day.

DKAN D8 Open Sprint Day
Friday, Aug 24, 10am-4pm in the Coders Lounge

On the final day of Drupal GovCon, stop by the Coders Lounge to see what the DKAN team is working on for our next major version. While we're still an early prototyping phase of DKAN on Drupal 8, there's already a lot to work on and some exciting architectural changes to discuss! Drop by, grab an issue if you are a developer (front-end or back-end), or just sit down to chat about the future of Open Data on Drupal with CivicActions engineers and others.
