### ISSUE TITLE
Blog post: U.S. Department of Transportation Chief Data Officer Dan Morgan to speak at 2018 DKAN Summit (2018 DKAN Summit)

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#161]
Bio:
Daniel Morgan is the first Chief Data Officer of the United States

Department of Transportation. As the CDO, he has overall responsibility for

the Departmental data program and data compliance across the Department. He

is responsible for establishing a clear vision of the data managed in DOT

and the application of DOT data for decision-making. He serves as data

strategist and adviser, steward for improving data quality, liaison for data

sharing and developer of new data products.

Prior to assuming this role, Mr. Morgan spent 15 years as a management

consultant, providing services to public and private sector clients in a

variety of areas, including: open government, information technology

governance, capital planning and investment control, enterprise

architecture, and human capital planning.

 

Mr. Morgan holds a Bachelor's Degree in Mechanical Engineering from the

University of Illinois at Urbana-Champaign.

Photo:

![morgan_speaker](https://user-images.githubusercontent.com/1569463/44226054-e9ab5280-a143-11e8-829f-61b3f6d44ae1.jpg)

**Comment by kimwdavidson** [comment]
Just waiting on talk name to publish
