### ISSUE TITLE
Recreate demo 'Flavor' builds on CA Jenkins

### ISSUE THREAD

**Issue by janette** [GetDKAN/ops#164]
- As an open data team member I would like a demo site to direct the public to.
- As an open data team member I would like a personalized demo site for testing things without having to build locally.

pick list: 
Dan
Daniel
David
Dharizza
Ero
Gerardo
Jacqueline
Janette
Kim
Stefanie

### Similar
 process as the DKAN 2 demo repo
https://github.com/GetDKAN/dkan/blob/7.x-1.x/.circleci/config.yml

### Difference
the flavor sites should build on a CA server and not the linode server

## DKAN 2 'Flavor' builds
- [ ] User should be able to log into Jenkins, pick name from a list, and trigger a build.
- [ ] DKAN2 sites should be built at [name].demo.d8.getdkan.com

**Comment by kimwdavidson** [comment]
will likely replace with some kind of one-click install solution. closing.
