### ISSUE TITLE
Recreate Acquia varnish queue processing task on CA Jenkins

### ISSUE THREAD

**Issue by janette** [GetDKAN/ops#165]
https://jenkins.nuamsdev.com/job/Data%20-%20Acquia%20Purge/

**Comment by dasumner** [comment]
Task requires updates to projects.rb and jenkinsTrigger.rb to handle split between two different Jenkins servers depending on job type.  Will submit PR for both today.

**Comment by erogray** [comment]
Passing to @janette for review

**Comment by janette** [comment]
merged https://github.com/NuCivic/jenkins_release_n_update_builds/pull/51
