### ISSUE TITLE
Recreate Security Scan task on CA Jenkins

### ISSUE THREAD

**Issue by janette** [GetDKAN/ops#166]
https://jenkins.nuamsdev.com/job/SecurityScan/

**Comment by dasumner** [comment]
Need to setup ZAP container on ci.civicactions.net and configure CA Jenkins to use it for this job.

**Comment by dasumner** [comment]
Security Scan Job has been recreated and confirmed to run and produce report.  Lesson learned: the OWASP ZAP plugin requires that ZAP be installed locally (on the Jenkins server).  The current setup is temporary.  Ideally, a job will bring up a Docker ZAP container, run the job and save the results to a permanent volume.  The new job is configured to run on the 15th.
