### ISSUE TITLE
Investigate google maps api key issue

### ISSUE THREAD

**Issue by janette** [GetDKAN/ops#168]
After switching the marketing site domain to `getdkan.org` and updating the google API restriction config, google is claiming the map api key is invalid

![map.png](https://images.zenhubusercontent.com/5361748905e96be61f00021c/77cabe5d-ee3c-4cfd-9091-e3d500cdb75b)

### google api config
![key.png](https://images.zenhubusercontent.com/5361748905e96be61f00021c/abdc6970-fce5-43f3-a232-fa9069c56a11)

**Comment by kimwdavidson** [comment]
fixed!
