### ISSUE TITLE
Set up Google Analytics for .org + demo. + docs.

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#2]
Set up analytics for:

- [x] getdkan.org
- [x] demo.getdkan
- [x] docs.getdkan

Add analytics to:

- [x] getdkan.org
- [x] demo.getdkan
- [x] docs.getdkan

## docs

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104306701-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-104306701-2');
</script>

## demo

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104306701-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-104306701-3');
</script>

**Comment by lukefretwell** [comment]
@grugnog thoughts on moving this forward?

**Comment by grugnog** [comment]
Analytics is set up for DKAN and DKAN Starter handbooks.

**Comment by lukefretwell** [comment]
@grugnog questions:

* Do we have analytics set for demo.getdkan?
* Do we have analytics set for docs.getdkan?
* If not, what's the best way to add? Use the same we're using for getdkan.org or create ones respective to each domain?
* Not a big deal, but can we get demo and docs changed from .com to .org?

**Comment by grugnog** [comment]
> Do we have analytics set for demo.getdkan?

Not that I know of

> Do we have analytics set for docs.getdkan?

Yes, I set that up (see above)

> If not, what's the best way to add? Use the same we're using for getdkan.org or create ones respective to each domain?

I would create a new property under the DKAN organization (I just made you an org admin) and use that for each domain/site.

> Not a big deal, but can we get demo and docs changed from .com to .org?

Yes, this is possible - docs should be easy but I haven't wrapped my head around what would be needed to do the same with demo.

**Comment by lukefretwell** [comment]
@grugnog 

I would create a new property under the DKAN organization (I just made you an org admin) and use that for each domain/site.

> So total of three properties? getdkan.org + docs.getdkan.org/.com + demo.getdkan.org/.com

**Comment by grugnog** [comment]
@lukefretwell Docs is set up (see above), but the other 2 would need to be created.

**Comment by lukefretwell** [comment]
I've set up analytics for the DKAN website, docs and demo.

@kimwdavidson @janette not sure who best to direct this to, but I've added the analytics code to top of this issue to be placed on those properties.

cc @grugnog

**Comment by dafeder** [comment]
I've added the GA code to demo.getdkan.

**Comment by janette** [comment]
@grugnog is this what you did? 
http://docs.readthedocs.io/en/latest/guides/google-analytics.html

**Comment by dafeder** [comment]
The wrong tracking code was in the config. I'm trying to add and rebuild

**Comment by dafeder** [comment]
I have changed the value in settings and the new code should be showing up in

https://docs.getdkan.com/en/latest/_static/readthedocs-dynamic-include.js

So far it's still showing the old one, but will check in a day or two and see if it's updated. Not sure how this stuff is cached.

**Comment by dafeder** [comment]
OK, I see the right tracking code there now. There seems to be some question about the way this code is generated on RTD. @lukefretwell let us know if the right data seems to be coming in, if not maybe we can stop using the RTD setting and see if there's a way to inject our own code in there.

**Comment by lukefretwell** [comment]
@dafeder still not seeing data in docs analytics.

**Comment by janette** [comment]
@lukefretwell are you seeing data for docs now?
