### ISSUE TITLE
DKAN newsletter or monthly touch-point

### ISSUE THREAD

**Issue by aaronpava** [GetDKAN/ops#23]
Are we doing anything to reach out to the "dkan in the wild" folks?  (ie Iowa and Nebraska are using DKAN) It would be nice to have a newsletter or some other touch point monthly.

**Comment by lukefretwell** [comment]
@aaronpava reminder (to myself) that I set up DKAN MailChimp.

**Comment by lukefretwell** [comment]
* add DKAN Summit attendees
* #12 https://github.com/GetDKAN/ops/issues/12
* create email newsletter sign-up
* customize mail template
* add link/embed to website
