### ISSUE TITLE
Conferences to promote DKAN and Open Data story

### ISSUE THREAD

**Issue by aaronpava** [GetDKAN/ops#24]
Suggested we attend the:
 - National Governors Association conference
 - Western Governors Association
 - Mid America Gis Consortium (has funding and DKAN users, many who are using it without support today)

The first 2 are where the competition is setting the plate by selling the vision from the top down. An open source open data story would totally play there.

**Comment by lukefretwell** [comment]
@andrewhoppin @stefaniefgray can you add a reference link here so we can see what we're working on? This should be specific to Project DKAN.

**Comment by andrewhoppin** [comment]
A reference link to what @lukefretwell ?   Stefanie's spreadsheet?

**Comment by andrewhoppin** [comment]
+1 on @aaronpava suggestions.  Plus, from my slack post of Oct 13, suggest Open Government Partnership Summit, International Open Data Conference, Code for America Summit, and whatever events What Works Cities puts on. 

Also suggest reviewing http://www.govtech.com/events/ for other ideas.
