### ISSUE TITLE
Edit new DKAN repo README

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#3]
Current: https://github.com/NuCivic/dkan/blob/7.x-1.x/README.md
New: https://gist.github.com/lukefretwell/a50ed08ae771e0d8bbfe8b3018621930

**Comment by lukefretwell** [comment]
@dafeder @janette who should this be assigned to?

**Comment by janette** [comment]
The new README has been merged https://github.com/NuCivic/dkan/pull/2189
