### ISSUE TITLE
Create DKAN Guide GitBook

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#30]
* https://www.gitbook.com
* create guide.getdkan.org subdomain
* sign up on GitBook via GitHub (https://www.gitbook.com/join)
* add @aaronpava @stefaniefgray @melindaburgess @andrewhoppin as collaborators
* sync /guide GitHub repo

**Comment by lukefretwell** [comment]
@grugnog I need either admin access here or your email to invite you as a DKAN GitBook admin sync GitBook to the getdkan GitHub org:

https://www.gitbook.com/@dkan/settings/github

... and the /guide repo:

https://github.com/GetDKAN/guide

... that will sync to this:

https://www.gitbook.com/book/dkan/guide/

**Comment by lukefretwell** [comment]
@grugnog just going to use wiki for ops and hopefully we can resolve the docs issues soon.

https://github.com/GetDKAN/ops/wiki

**Comment by lukefretwell** [comment]
Still not sure about this. For example, values and code of conduct would be something that would be great to have in a guide or handbook that might not fit into documentation.

**Comment by lukefretwell** [comment]
@aaronpava @andrewhoppin can the two of you create a GitBook account using your GitHub?

https://www.gitbook.com/join

**Comment by grugnog** [comment]
@lukefretwell I would suggest we talk about this with the DKAN team/community. I am not clear why values and code of conduct couldn't live in the current handbook. Also, having multiple sources of documentation living in different places and managed by totally different tools/workflows sounds like it could get confusing and disjoint for both users and maintainers.

**Comment by lukefretwell** [comment]
@grugnog we're going to start by compiling all the information we need into a format that's easy for us to build and manage. Once there's a reliable foundation/process for updating/expanding docs, let's discuss whether it makes sense to move some or all of the information from here to there.

I've moved all the information relevant to ops/community here and, of course, it's still a work in progress, so this will change:

https://dkan.gitbooks.io/guide/content/

cc @aaronpava @melindaburgess @andrewhoppin @stefaniefgray

**Comment by grugnog** [comment]
@lukefretwell just to confirm - there is an existing process for updating and expanding docs, which is to make a pull request to the project repository (https://github.com/NuCivic/dkan). This the standard process for contributing anything to DKAN or any open source project hosted on GitHub. As before, I am happy to walk you through this process if you would like.
