### ISSUE TITLE
Create DKAN values draft #1

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#31]
Working doc:

https://docs.google.com/document/d/1kuV4gXuK3xLRWF11Wjajeh7cuN5q1Gcu7GG2GT0b8OI/edit?usp=sharing

**Please requesting edit access via the doc.**

**Comment by acouch** [comment]
"Open Data is not truly open if the tools used to publish and consume it are not open as well"

**Comment by lukefretwell** [comment]
@acouch see doc I started:

https://docs.google.com/document/d/1kuV4gXuK3xLRWF11Wjajeh7cuN5q1Gcu7GG2GT0b8OI/edit?usp=sharing

**Comment by kimwdavidson** [comment]
Values statement work in progress here: https://docs.google.com/document/d/1Nsx_kZ32WtzgIsttOlbjZZmOAJ7bNx5dofZyPfSSwuU/edit?usp=sharing

**Comment by kimwdavidson** [comment]
Next steps:
- Review against Open Data Principles
- Project DKAN team to comment by Thursday
- Thursday create plan for pushing it out and call for feedback.

**Comment by lukefretwell** [comment]
@kimwdavidson looks like there are three docs where DKAN values is referenced (see first one in issue thread: https://docs.google.com/document/d/1kuV4gXuK3xLRWF11Wjajeh7cuN5q1Gcu7GG2GT0b8OI/edit?usp=sharing).

Can we create one using [DKAN doc template](https://docs.google.com/document/d/1K1sU9H2vPN5tnXqW7jQO2OCIM1TwEiC8AfNQv9k64PA/edit), merge comments/info into one and remove references in the other two so there's no confusion as to where this is and it has the DKAN styles? Let me know if you'd like me to to, just don't want to step on your toes.

**Comment by lukefretwell** [comment]
@kimwdavidson @fmizzell @stefaniefgray I've consolidated to this doc:

https://docs.google.com/document/d/1kuV4gXuK3xLRWF11Wjajeh7cuN5q1Gcu7GG2GT0b8OI/edit?usp=sharing

**Comment by kimwdavidson** [comment]
Kim to consolidate back down to five-ish values with short descriptions. Have ready for sharing with the community Thursday

**Comment by kimwdavidson** [comment]
Feedback process:
- Promote (use this as a template: https://trello.com/c/3d95uOq3/678-promote-template)
- Feedback period goes until the 22nd
- Give feedback by commenting on the doc
