### ISSUE TITLE
Update demo.getdkan

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#4]
Reference: http://demo.getdkan.com/

Pages:

* [x] Remove content here: http://demo.getdkan.com/about ...
* [x] and add 'Learn more about DKAN: [getdkan.org](https://getdkan.org)'
* [x] change footer text to: Powered by <a href="https://getdkan.org">DKAN</a>

**Comment by lukefretwell** [comment]
@grugnog @stefaniefgray @janette who can lead on this?

**Comment by janette** [comment]
@lukefretwell the footer was fixed today. What do you want done with the About page? change it to a link? This is a placeholder page for users to experiment with.

**Comment by janette** [comment]
@lukefretwell still unclear what should happen with the about page, it seems like you want to remove the list of features and replace with a) marketing lingo or b) a link? Please clarify

**Comment by lukefretwell** [comment]
@janette yes, just remove that copy and replace with this:

Learn more about DKAN: [getdkan.org](https://getdkan.org/)
