### ISSUE TITLE
Review/update DKAN features language

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#41]
- [ ] consolidate/edit DKAN features language ( [working doc](https://docs.google.com/document/d/11X8SY962hrfRx9sWRruZW62hNg8D9qTQ_ARiR__Bbqg/edit?usp=sharing) )
- [ ] add updated verstion to 'Features' section of docs.getdkan
- [ ] add any relevant icons to getdkan.org features section
- [ ] update on DKAN deck
- [ ] create /features page

**Comment by stefaniefgray** [comment]
Please QA, let me know if anything needs further changes: https://docs.google.com/document/d/11X8SY962hrfRx9sWRruZW62hNg8D9qTQ_ARiR__Bbqg/edit#
