### ISSUE TITLE
Community updates

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#44]
- [x] Add a /community page to docs
- [x] [Use this copy](https://docs.google.com/document/d/1QgRbVsPgiixmK8gcEP_356y-KBROGx4mNHJj9jXqWjs/edit?usp=sharing)
- [x] Connect with DKAN Slack admin
- [x] Post to Slack #general channel
- [x] Delete [doc](https://docs.google.com/document/d/1QgRbVsPgiixmK8gcEP_356y-KBROGx4mNHJj9jXqWjs/edit?usp=sharing)
- [x] https://github.com/GetDKAN/website/issues/18

@janette working on copy now. @kimwdavidson is there conduct copy?

**Comment by lukefretwell** [comment]
@janette FYI the doc is updated. Thank you!

**Comment by janette** [comment]
@lukefretwell  http://dkan.readthedocs.io/en/latest/community/code-of-conduct.html

**Comment by kimwdavidson** [comment]
Items are completed except website 118. Closing for that one.
