### ISSUE TITLE
Create info@getdkan.org email address

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#45]
@grugnog thoughts on setting this up under the getdkan@gmail.com account?

**Comment by grugnog** [comment]
This is set up and appears to be working (both send and receive). I used a free Mailgun account for forwarding thanks to the helpful directions at https://www.chrisanthropic.com/blog/2014/mail-forwarding-with-mailgun-and-cloudflare/

**Comment by lukefretwell** [comment]
Thank you!
