### ISSUE TITLE
"Sheet template" should read "Slides template" in wiki. and change permissions to wiki.

### ISSUE THREAD

**Issue by kevwalsh** [GetDKAN/ops#47]
"Sheet" on https://github.com/GetDKAN/ops/wiki/Templates should be "Slides". (sheets are for spreadsheets). 

I can't edit the wiki, i guess you have to be a collaborator on the repo.

**Comment by lukefretwell** [comment]
@grugnog what's the most efficient way to give access to the wiki?

**Comment by kevwalsh** [comment]
@lukefretwell https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by lukefretwell** [comment]
@grugnog I helped @kevwalsh (showed him how to accept member invite 🙄 )
