### ISSUE TITLE
Social media strategy

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#49]
Reference doc with more details: https://docs.google.com/document/d/1llIBP9ofpY0hZLLN5B1O__T8AtZpkc1CAXNEySRnees/edit#

-----
Tasks for @stefaniefgray

**Facebook**
- [ ] Set up an account registered to a GetDKAN email address.
- [ ] Create a "set it and forget it" DKAN page that links to other DKAN social media links, documentation, and the Slack network.
- [ ] Modify branding of page to match DKAN branding.
- [ ] Link to Medium.

**LinkedIn**
- [ ] Create a DKAN-specific LinkedIn page, if there isn't one already.
- [ ] Modify branding of page to match DKAN branding.
- [ ] Link to Medium.

**Reddit**
- [ ] Create GetDKAN account.
- [ ] Register r/GetDKAN subreddit.
- [ ] Create a "set it and forget it" post about DKAN (see above).

**Twitter**
- [ ] Log in as GetDKAN
- [ ] Update branding of page, if necessary.
- [ ] Unfollow irrelevant and inactive accounts.
- [ ] Follow relevant accounts.
- [ ] Delete any old tweets referencing GovDelivery/Granicus
- [ ] Link to Medium

**Comment by lukefretwell** [comment]
@stefaniefgray let's find 30 minutes next week to co-work on this.

**Comment by stefaniefgray** [comment]
https://docs.google.com/a/civicactions.net/document/d/1W0SvUIFIe5l4aDlBGz_SRHDmH0RbmfVjwt9IgKYbNXs/edit?usp=sharing

**Comment by lukefretwell** [comment]
@stefaniefgray here are the brand assets: https://github.com/GetDKAN/ops/wiki/Brand

**Comment by kimwdavidson** [comment]
Let's break each property into its own ticket and close this one.

**Comment by lukefretwell** [comment]
@stefaniefgray I moved newsletter tasks to https://github.com/GetDKAN/ops/issues/33
