### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#5]
Related issues:

* https://github.com/NuCivic/dkan/issues/2046
* https://github.com/NuCivic/dkan/issues/2045
* https://github.com/NuCivic/dkan/issues/2044
* https://github.com/NuCivic/dkan/issues/2043

+

incorporate this information when ready:

https://dkan.gitbooks.io/guide/content/

**Comment by stefaniefgray** [comment]
Docs are updated on scratch branch; waiting for Justin to review for they can be pushed to primary branch.

**Comment by janette** [comment]
@stefaniefgray the only scratch branch I found was `stefanie_docs_scratch_1` and the changes on that branch were already merged from somewhere else it seems.

@lukefretwell the issues in dkan 2046, 2045, 2044, and 2043
are addressed here https://github.com/NuCivic/dkan/pull/2190

**Comment by janette** [comment]
@lukefretwell you can review here: http://dkan.readthedocs.io/en/stefanie-docs/

**Comment by lukefretwell** [comment]
@janette looks great. Thank you!

**Comment by lukefretwell** [comment]
@janette related to docs update, can we do a clean sweep on removing references to GovDelivery, NuCivic.

Note 'DKAN is maintained by GovDelivery.' on main page:

http://docs.getdkan.com/en/latest/introduction/index.html
