### ISSUE TITLE
Create DKAN overview deck

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#50]
- [ ] review docs for inclusion

Working deck: 

https://docs.google.com/presentation/d/10qo7XI8dQCfDwlMu2hWAErBVV1cV4kAn62oDwCI7Ew4/edit?usp=sharing

Reference via @stefaniefgray: https://docs.google.com/a/civicactions.net/presentation/d/18OaIGLEnt1FwhNIZu82w5rcP5t5s5LCULQO3NMCbVJ4/edit?usp=sharing

**Comment by kimwdavidson** [comment]
@lukefretwell and @stefaniefgray to sync on their materials and make sure they're making best use of new and existing assets.

**Comment by stefaniefgray** [comment]
https://docs.google.com/presentation/u/1/d/10qo7XI8dQCfDwlMu2hWAErBVV1cV4kAn62oDwCI7Ew4/edit?usp=slides_home&ths=true

Closing ticket for now

**Comment by lukefretwell** [comment]
@stefaniefgray can we resolve the current comments first, whether in the deck or in new issues for the backlog?

**Comment by lukefretwell** [comment]
* Added to https://getdkan.org/resources/
* Posted to blog: https://medium.com/@getdkan/dkan-deck-790ef06e89ea
