### ISSUE TITLE
Define the purpose of the GetDKAN/ops repo in the README.md file

### ISSUE THREAD

**Issue by marctjones** [GetDKAN/ops#53]
What is the scope of the GetDKAN/ops repo? what issues should be going here as oppose to the regular DKAN repo?

Why are they seperate from that?

For instance this issue in the DKAN repo is about adding ideas to a Roadmap? Is creating a road map a "ops" issue? https://github.com/GetDKAN/dkan/issues/2150

**Comment by marctjones** [comment]
Who is responsible for this issue queue and how does it relate to the issue queue that is in the DKAN repo? or any trello boards that @kimwdavidson  as the DKAN PM is managing

**Comment by lukefretwell** [comment]
@marctjones I updated readme to clarify more. As far as Trello boards @kimwdavidson is managing, those are most likely related to internal CA work and not Project DKAN.
