### ISSUE TITLE
People/team clean-up

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#56]
@grugnog looks like the work we did on this got overridden by the repo transfers.

Would you mind being point on:

- [ ] review people (remove and/or update privileges) (https://github.com/orgs/GetDKAN/people)
- [x] make sure they've enabled 2FA
- [ ] review (delete?) teams (https://github.com/orgs/GetDKAN/teams)
- [ ] + make team members public (current can only see 3 people when not an admin or member of the org)

**Comment by grugnog** [comment]
I think @kimwdavidson and @dafeder may have set this up yesterday

**Comment by lukefretwell** [comment]
@kimwdavidson @dafeder did you? If so, let's discuss on tomorrow's call.

Initially @grugnog and I removed the teams and cleaned up the people and respective access to.

**Comment by lukefretwell** [comment]
@dafeder @kimwdavidson @grugnog:

* Do we need these teams? If no, can I delete?
* Is there anyone in the [people](https://github.com/orgs/GetDKAN/people) list that should be removed?
* Is there anyone in the [people](https://github.com/orgs/GetDKAN/people) list that should be added?

**Comment by dafeder** [comment]
* Yes, we need the teams, this is how permissions are organized in Github. What is the problem/issue with them?
* Everyone in the people list should be there.
* Not sure if there's anyone missing, I and others can add as needed.
* The squirrel is the Jenkins machine, I'll look into getting that invite accepted. One of the four invites was made in error. Bob and Iris, sure you can follow up.
* Once we get the squirrel added to the team, we can remove as an outside collaborator.

**Comment by lukefretwell** [comment]
@dafeder thank you. Going to close this, but if you could handle anything related to the squirrel, that would be great.
