### ISSUE TITLE
Homepage updates

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#57]
* search-replace https://github.com/NuCivic/dkan with https://github.com/GetDKAN/dkan
* search-replace https://getdkan.github.io/dkan-sites/ with http://docs.getdkan.com/en/latest/introduction/dkan-sites.html
* remove @lukefretwell

**Comment by janette** [comment]
@lukefretwell the list of dkan sites needs to be updated, not accurate at the moment

**Comment by lukefretwell** [comment]
@janette OK can you address last bullet?

**Comment by janette** [comment]
@lukefretwell the `remove @lukefretwell ` ? remove from where?
