### ISSUE TITLE
Determine Project DKAN Retrospective Process

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#58]
Done: https://github.com/GetDKAN/retrospective

cc @kimwdavidson @stefaniefgray

**Comment by kimwdavidson** [comment]
The CivicActions retro process could work really well for this - A Trello board for the community to add to?

**Comment by lukefretwell** [comment]
@kimwdavidson @stefaniefgray @fmizzell just to follow up, a Trello board or 'Retro Repo' works for me. What I like about the repo is that we can reference issues in other repos in addressing feedback. 

I'll get the repo set up if that's the direction we want to go.
