### ISSUE TITLE
DKAN Summit wrap-up post

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#6]
* Photos: https://photos.app.goo.gl/KKGUPccstWzJUFWA3
* Presentations

**Comment by stefaniefgray** [comment]
@melindaburgess and I are currently taking notes for the post in this doc: https://docs.google.com/document/d/1Od35uRcc5WWLggPt7Jkx2mN15wSK5xxs9m8EgGNckBE/edit

**Comment by melindaburgess** [comment]
@lukefretwell My Medium username is melinda.burgess

**Comment by lukefretwell** [comment]
+ add link to wrap-up post here: https://getdkan.github.io/website/summit/index.html

**Comment by lukefretwell** [comment]
Published: 

https://medium.com/dkan-blog/highlights-2017-dkan-open-data-summit-5b7a4a9710e0
