### ISSUE TITLE
Define Roadmap Structure MVP

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/ops#60]
Suggested structure:
- Is public
- includes next three features and unprioritized features we know we'd like in the next year or so

**Comment by kimwdavidson** [comment]
Gerardo's taken a first stab: https://docs.google.com/document/d/1Hu1AVn6gRCCXdwyCNKe66muAljO8Z9qqf5Ev69xyDBI/edit#heading=h.r2ndiahl5at

Looks like it might be too big and long term to be fulfill all our needs, but a hybrid between this and the original concept, might be perfect. Let's continue to discuss.

**Comment by lukefretwell** [comment]
@kimwdavidson this is in 'Done,' so OK to close this issue?
