### ISSUE TITLE
Determine release announcement process

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/ops#63]
Use promote template to promote

Content
- We've released DKAN version x
- What was done in this release
- What's coming up next (maybe later)
- Link to release on Github
- How to get involved, including social media

Dan's current format: https://github.com/GetDKAN/dkan/releases/tag/untagged-6e8e090aa64de73101e7

[ ] Get this into a blog format
[ ] Update format to include how to get involved/social media

**Comment by lukefretwell** [comment]
@kimwdavidson this is in 'Done,' but is it documented anywhere?

**Comment by kimwdavidson** [comment]
How to get involved text:

Want to get involved with DKAN? Join the conversation on Slack; submit suggestions or bugs to the Github issue queue; follow the blog; or find us on Facebook, Twitter, LinkedIn, Medium, or Reddit.
