### ISSUE TITLE
Close DKAN developer list

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/ops#66]
- [ ] post announcement through December 15
- [ ] export email contacts
- [ ] send email contacts for how to get involved
- [ ] get admin access
- [ ] close group

From ahoppin:

worth noting that there are still occasional questions being asked on the DKAN Developer list (https://groups.google.com/forum/#!forum/dkan-dev) going unanswered; possible for someone to monitor and triage periodically, as with the Slack?  or at least respond there directing people to slack to ask the q?

**Comment by kimwdavidson** [comment]
[ ] Ask people of they're using it

- Everyone's talking in Slack, do we need this?

**Comment by kimwdavidson** [comment]
Let's plan to close this down. 

[ ] Luke to write announcement
[ ] Let's post a once/week reminder that we're closing this down. 
[ ] Close this December 15th.

**Comment by lukefretwell** [comment]
@kimwdavidson do we know who the admin is for this? I don't have access to close it.

Thoughts on this message?

Subject: Closing DKAN Developers Group December 15

Body:

Hi all,

Much of the communications around DKAN is happening outside of this DKAN Developers Google Group. To better manage and service all of the conversations around DKAN, our plan is to close this group on December 15.

There are several ways to connect with the active aspects of the DKAN community, all of which you can find here:

https://getdkan.org/community/

If you have questions, please post here or email us at info@getdkan.org.

Reference: https://github.com/GetDKAN/ops/issues/66

Luke

**Comment by kimwdavidson** [comment]
Kim to make Luke an admin

**Comment by lukefretwell** [comment]
@kimwdavidson ^^ can you make me an admin?

**Comment by lukefretwell** [comment]
@dafeder @kimwdavidson I've made four announcements to the group that we're closing it. Is it possible to get admin rights to update the notice and/or delete? I'd also like to see if there's a way to get the email addresses so we can send a notice just in case folks don't get them via group postings.

**Comment by lukefretwell** [comment]
Thanks @dafeder. Don't see a way to delete the group, but changed the welcome message and group description to indicate it's no longer being maintained with link to /community for info on how to get involved. Also exported member emails I'll send a note to.

**Comment by lukefretwell** [comment]
@dafeder @kimwdavidson here's what I've done:

* updated group welcome message and description to indicate it's no longer active
* sent email to current members telling them it's closed and how to connect with the community

If either of you can delete the group, that would be great. 

Closing this issue.
