### ISSUE TITLE
D7-D8 transition plan

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/ops#70]
From Marc's suggestions
- should include the approximate end of life for new product development on the D7 version (i.e. no new featues), 
- the target for having a initial release, betas, and production ready version of the D8 release.

That way 1) we communicate the long term lifecycle to potential adopters and we are starting to give us a framework to talk about how much we want to invest in the current version, verse putting future enhancements into the D8 version.

**Comment by lukefretwell** [comment]
@kimwdavidson I'm closing this since it's on the product roadmap and more relevant for /dkan repo.
