### ISSUE TITLE
Promote 1.14 release

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/ops#72]
## Blog

How to contribute to the [DKAN blog](https://medium.com/dkan-blog):

* [ ] Create a shared, commentable Google doc (use [this template](https://docs.google.com/document/d/1K1sU9H2vPN5tnXqW7jQO2OCIM1TwEiC8AfNQv9k64PA/edit?usp=sharing)).
* [ ] When done, add a link to the Google doc to this issue (see 'Doc for review' below) with edit access for getdkan@gmail.com.
* [ ] Once editorial is finalized, publish your post to [Medium](https://medium.com/).
* [ ] Add your Medium username (see 'Medium username' below) to the GitHub issue ticket, we'll add you as a contributor and publish your post to the DKAN blog.

* Doc for review: 
* Medium username: 

## Promote

Checklist for promoting DKAN releases, blog posts and other news:

* [ ] Blog post (Instructions: https://github.com/GetDKAN/ops/wiki/Blog)
* [ ] Post to Twitter: https://twitter.com/getdkan
* [ ] Post to [DKAN Slack](https://dkan.slack.com) in #general, #buzz, or other relevant channels

Content

- We've released DKAN version x
- What was done in this release
- What's coming up next (maybe later)
- Link to release on Github
- How to get involved: "Want to get involved with DKAN? Join the conversation on Slack; submit suggestions or bugs to the Github issue queue; follow the blog; or find us on Facebook, Twitter, LinkedIn, Medium, or Reddit."
- Dan's current format: https://github.com/GetDKAN/dkan/releases/tag/untagged-6e8e090aa64de73101e7

**Comment by lukefretwell** [comment]
Done: https://medium.com/dkan-blog/dkan-1-14-b9731d7ca181
