### ISSUE TITLE
Move promote template to wiki

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/ops#74]
[ ] Copy this ticket when we have something to promote and retitle it Promote: xxx
[ ] Blog post (Instructions: https://github.com/GetDKAN/ops/wiki/Blog)
[ ] Twitter @ 1-3 p.m. (twitter.com/getdkan)
[ ] DKAN Slack in #general, #buzz, or other relevant channel (dkan.slack.com)

**Comment by lukefretwell** [comment]
@kimwdavidson @fmizzell I figured out the issue template, so now when you create a new issue, it'll populate a number of pre-made to-dos to edit/delete.

See: https://github.com/GetDKAN/ops/issues/new
