### ISSUE TITLE
Put values out for review

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/ops#75]
https://docs.google.com/document/d/1kuV4gXuK3xLRWF11Wjajeh7cuN5q1Gcu7GG2GT0b8OI/edit#heading=h.fanfulsyabp

use promote template to promote.

Close comment period 11/22/17

**Comment by lukefretwell** [comment]
@kimwdavidson @fmizzell @stefaniefgray any feedback on the blog post?

https://docs.google.com/document/d/1Q5z-cLGCMoGBPCvKksTZyVBTWlxcOiUoVj6c9dsdBn4/edit?usp=sharing

**Comment by kimwdavidson** [comment]
Looks good to me!
