### ISSUE TITLE
Remind public about values comment period

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/ops#80]
Original post: https://medium.com/dkan-blog/drafting-dkan-values-44135337183a

* [x] Write text
* [x] Post to Twitter: https://twitter.com/getdkan
* [x] Post to [DKAN Slack](https://dkan.slack.com) in #general, #buzz, or other relevant channels

**Comment by stefaniefgray** [comment]
@kimwdavidson @lukefretwell:

Post (for email and Slack)
-------------

Hi folks,

As mentioned in our most recent blog post, we are continuing to set a new foundation for Project DKAN, and we wish to establish core values that exemplify the principles of the DKAN community.

The deadline for initial feedback - November 22nd - is swiftly approaching, leaving us with only a week to continue to collect public input from the open data community at large.

If you'd like to pitch in, please take a moment to check out the DKAN values draft document, hosted on Google Docs. Feel free to provide comments and input!

We can't wait to see what comes of Project DKAN in 2018 and beyond, and we look forward to continuing to build on an open, proactive collaboration between DKAN and the communities it serves.

Best regards,
Stefanie Gray
Project DKAN

-------------
Possible Tweets
-------------

- Calling all open data users and innovators! Help us collect community input for Project DKAN and its values: [link]

- The initial deadline for contributing to the DKAN Values document - a crucial part of Project DKAN to come - is Nov. 22. Check it out!: [link]

- What does open data mean to you? What are the values behind open data and transparency? Let us know, and help contribute to Project DKAN's values! [link]

**Comment by stefaniefgray** [comment]
^^ Let me know if these look good, and I'll blast 'em out today (though the tweets, if they're all good-to-go, can be spaced out to every 24-48 hours between today and the 22nd)
