### ISSUE TITLE
Redirect dkansummit.org to getdkan.org/summit

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#82]
dkansummit.org needs to be redirected to to getdkan.org/summit

**Comment by aaronpava** [comment]
@lukefretwell @grugnog 

I transferred ownership to 'civicactions' Namecheap account.

https://www.evernote.com/l/AASMcWq6RWRKObMXcHKq7Llk4UB4Gfh1gu8B/image.png

**Comment by grugnog** [comment]
Wildcard redirect set up - may take a while for nameservers to update before it is active

**Comment by lukefretwell** [comment]
@grugnog @aaronpava thank you!

**Comment by grugnog** [comment]
@lukefretwell realized that .org was not transferred - only .com, so transferred that. Both should now be unparked (which was the problem with .com) and have identical redirect configs. dkansummit.com is not redirecting for me yet - but it should once the DNS updates.
