### ISSUE TITLE
Add HTTPS to demo.getdkan + docs.getdkan

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#89]
We need to add HTTPS (+redirect) to:

- [ ] http://docs.getdkan.com/en/latest/
- [ ] http://demo.getdkan.com/

**Comment by grugnog** [comment]
Docs is done - demo has HTTPS set up on CloudFlare (I think, although it is erroring right now?). I think demo needs some additional config to make it work on https though.
