### ISSUE TITLE
DKAN + Open Data Day

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#94]
Anyone have ideas on how DKAN can get involved with Open Data Day?

Details: http://opendataday.org/

- [x] set up Google Doc (https://docs.google.com/document/d/1xijgObA410hzRsfwFHiJROxJRI0qfpG0k9SOCXqJbPQ/edit?usp=sharing)
- [x] set up /opendataday (https://getdkan.org/opendataday/)
- [x] reach out to Open Data Day leadership
- [ ] add to wiki when appropo
- [ ] register DKAN event (if relevant): https://docs.google.com/forms/d/e/1FAIpQLSerBbFdsz0nBdtfPWVN9aWoPopX5-lKGfsFFjz6pzz95OLu_A/viewform
- [ ] create reg form (?)
  
- [ ] post here: https://groups.google.com/forum/#!topic/open-data-day/TpD-g9eg8yk
- [ ] create Slack channel (Done: https://dkan.slack.com/messages/C8MB3AF7C/details/?)
- [ ] DKAN + Open Data Day blog post

**Comment by stefaniefgray** [comment]
We could harness lots of energy/power/code from the community through a hackathon -- especially if we created one with the intention of fixing some of the modules that are keeping us from properly displaying previews of open data. (Our biggest issue with dataset publishing at the moment, in my opinion.)

For example, if people could get together to help fix the DKAN choropleth module, we'd be able to show full color maps created within DKAN, which would also revolutionize Data Dashboards and Data Stories.

Or what if we were able to get people to help implement a QGIS2WEB plug-in within DKAN, which would also help expand our open geospatial data display capabilities?

Hackathons definitely need incentives/prizes though, so a hefty Amazon gift card or something along those lines would be good to offer.

**Comment by stefaniefgray** [comment]
We should also be keeping track of where Open Data Day events are located (there's a map on the main site that'll be updated with each one) and make sure that some CivicActions folks can attend in person.

**Comment by mgottholsen** [comment]
We've run quite a few hackathons here in Louisville, and we've seen great success with having a few pre-identified ideas for groups to focus on, but then also leaving room for those random, spur of the moment ideas. Clearly identifying problems, features etc tends to help a lot, documenting requirements, and what the MVP looks like.

I would love to see all the different entities that use DKAN involved in some way. We all have our own development groups (mostly), and if we all worked together on DKAN, I think we could see some really neat things. This possibility for collaboration is what initially attracted us to DKAN.

One of the pain points we experience with DKAN is an automated way to update the data on it. Currently all of our data is internal, on an IIS server. We have an api that serves these files, but is slated for deprecation. We pull these files from the api using curl, and then a few of the dataset drush commands to update the resource files. This is really clumsy, and we've always wanted a better way to handle these things. So that could be something.

I'd like to get some thoughts from Michael Schnuerle, our Data Officer. I think he'd have a few ideas as well.

**Comment by schnuerle** [comment]
I think we can get some interest drummed up in Louisville with our Code for America brigade.  The goal would be to improve Louisville’s open data site! Open source collaboration is always exciting. We can prioritize issues we have and features we'd like and line up some solutions. And work with directly with the groups on the day of event. Aligns very well with Open Data Day.   

Louisville talked with DKAN about this a few times around a year ago.  Having an international focus for editing DKAN with participation from cities/states/orgs that use DKAN would be very powerful and successful I think.  Maybe this would be a good start, then it could be its own DKAN Day later in the year.

**Comment by lukefretwell** [comment]
@mgottholsen @schnuerle thank you for the input! We'll follow up on this soon.

**Comment by kimwdavidson** [comment]
Hi @mgottholsen and @schnuerle! We'd love to work with you on something for Open Data Day. A hackathon sounds great, and we've got a a few ideas of how to format one, but it sounds like you've got a lot more experience organizing them. Do you have time to get on a call sometime early next week, maybe Tuesday afternoon to talk more? Thanks!

**Comment by lukefretwell** [comment]
Added page to DKAN site: https://getdkan.org/opendataday/

**Comment by lukefretwell** [comment]
@kimwdavidson any updates on this? We should get a blog post out in the next week or so.

**Comment by lukefretwell** [comment]
@kimwdavidson we're sending a DKAN newsletter this week. Would be great to have some way to capture folks who are interested in participating, perhaps via an Eventbrite with different attendee types (onsite / remote). Let's discuss on our Tuesday check-in.

**Comment by schnuerle** [comment]
I've been updating the collab doc with a bunch of stuff and ideas.  Other cities should add their project ideas and locations too:  https://docs.google.com/document/d/1xijgObA410hzRsfwFHiJROxJRI0qfpG0k9SOCXqJbPQ/edit

**Comment by mgottholsen** [comment]
I've looped in our local Code for America chapter, Civic Data Alliance so we can try and keep the conversation in one place for simplicity.

**Comment by cheapwebmonkey** [comment]
We, [CDA](http://civicdataalliance.org),  the local Louisville Code for America Brigade are hosting a hackathon that centers around how to implement the Open Data portal in Louisville in a project and how to leverage it for information if you are a non-dev/builder citizen. Happy to post a link to the event once we have to together. but here is the gist:

Projects for ODD:
1. Open Data Workshop
2. D4D Data Science Ethics Project

I'm working on the language for the event, so far I have:
What is open data?
What can it be used for?
Why is it important?
Where can I find it?

For Code for America’s Open Data Day on March 3, 2018, Civic Data Alliance, in conjunction with OPI2, presents a workshop on Open Data and Louisville Metro’s Open Data Portal. We want to be a force for educating the general public on what open data is and how it can be used for our community. As members of the data community, we believe it is imperative to create avenues for our greater Louisville community to understand, implement, and manipulate open data and the Open Data Portal in the spirit of transparency and civic engagement. 

Besides the Open Data Workshop, we will also have the opportunity to work on The Code of Ethics in Data Science project with Data for Democracy featured in this article (link to article), as well as other projects. 

CDA advocates for openness and transparency in data from our government and for these same principles in our government itself, including it’s officials, actions, policies, procedures and departments. 

Part of advocating for and being an open and transparent civic organization is advocating for openness and transparency in all civic areas. 

Open Data. Open Gov. Open ALL the things.
